name = "qistudio"
compatibility_date = "2026-07-30"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "qistudio-rdv-db"
database_id = "dcd69b35-b466-4b6e-a3c8-336fc7a85b97"
